version: '3'
name: 'logique-app'

networks:
  logique_app:
    driver: bridge
    
volumes:
  mongodb_data:

services:
  app:
    build: ../app
    networks:
      - logique_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - logique_app
    ports:
      - "27017:27017"